/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Mon Oct 17 13:58:38 2016. */

#include "measurement.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t api_Measurement_fields[6] = {
    PB_FIELD(101, UINT32  , OPTIONAL, STATIC  , FIRST, api_Measurement, motion, motion, 0),
    PB_FIELD(102, UINT32  , OPTIONAL, STATIC  , OTHER, api_Measurement, water, motion, 0),
    PB_FIELD(103, UINT32  , OPTIONAL, STATIC  , OTHER, api_Measurement, temperature, water, 0),
    PB_FIELD(104, FLOAT   , OPTIONAL, STATIC  , OTHER, api_Measurement, humidity, temperature, 0),
    PB_FIELD(110, UINT32  , REPEATED, CALLBACK, OTHER, api_Measurement, analog_readings, humidity, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
