/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Mon Oct 17 13:58:38 2016. */

#ifndef PB_MEASUREMENT_PB_H_INCLUDED
#define PB_MEASUREMENT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _api_Measurement {
    bool has_motion;
    uint32_t motion;
    bool has_water;
    uint32_t water;
    bool has_temperature;
    uint32_t temperature;
    bool has_humidity;
    float humidity;
    pb_callback_t analog_readings;
/* @@protoc_insertion_point(struct:api_Measurement) */
} api_Measurement;

/* Default values for struct fields */

/* Initializer values for message structs */
#define api_Measurement_init_default             {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define api_Measurement_init_zero                {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define api_Measurement_motion_tag               101
#define api_Measurement_water_tag                102
#define api_Measurement_temperature_tag          103
#define api_Measurement_humidity_tag             104
#define api_Measurement_analog_readings_tag      110

/* Struct field encoding specification for nanopb */
extern const pb_field_t api_Measurement_fields[6];

/* Maximum encoded size of messages (where known) */
/* api_Measurement_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MEASUREMENT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
