/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Oct 13 18:18:03 2016. */

#include "measurement.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t api_Measurement_fields[3] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, api_Measurement, motion, motion, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, api_Measurement, water, motion, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
